admin_panel/urls.py
from django.urls import path
from . import views


app_name = 'admin_panel'
urlpatterns = [
    path('client-dfn23423nroi2rvi32inc23px3p23ppm2/', views.clients, name='clients'),
    path('delete-client-adjn23jnjcn234c3m54cp34mmp/<str:phone_number>/', views.delete_client, name='delete-client'),
    path('main-information-j2nnl453k4vn3o4n534c343/', views.main_information, name='main-information'),
    path('add-main-information-anj23j2nc3n423nc233/', views.add_main_information, name='add-main-information'),
    path('delete-main-information-po23pjp23po2c323/', views.delete_main_information, name='delete-main-information'),
    path('add-place-jnerntenrt3i534590293v2oij2343/', views.add_place, name='add-place'),
    path('delete-place-woktokyrono4nvb4353435d2dr2/', views.delete_place, name='delete-place'),
    path('add-media-23n2b4iu4hco34icp34pii34ncn3c4/', views.add_media, name='add-media'),
    path('delete-media-2j3n23cm4mc34nc3434c34pm34o/', views.delete_media, name='delete-media'),
    path('add-book-2342534c34pp3c4p3j4vpjij4cir3pi/', views.add_book, name='add-book'),
    path('delete-book-jn34jn4kc34b5jc43nlk6778m987/', views.delete_book, name='delete-book'),
    path('add-faq-jndkjfgnkdjf3234h4n5v85v09j92jv9/', views.add_faq, name='add-faq'),
    path('delete-daq-3i4pooij3pn34i6in6n756jn7n78n/', views.delete_faq, name='delete-faq'),
]

landing_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('clients-management-system/', admin.site.urls),
    path('', include('lp.urls', namespace='lp')),
    path('admin-panel/', include('admin_panel.urls', namespace='admin_panel')),
    path('authentication/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lp/urls.py
from django.urls import path
from . import views


app_name = 'lp'
urlpatterns = [
    path('', views.index, name='index'),
    path('get-main-information-32n42n56bh67bkj45kjnk324n5/', views.get_main_information, name='get-main-information'),
]

users/urls.py
from django.urls import path
from . import views
from .assistants import generate_token


app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('get-phone-number-jnsdfc242cc4342c323ch2h3ch234c23/', views.get_phone_numbers, name='get-phone-numbers'),
]

lp/models.py
from django.db import models
from .relations import SocialMedia


class Book(models.Model):
    """
    A model for handling books released by the learning center.
    """

    name = models.CharField(max_length=200)
    file = models.FileField(upload_to='files')

    objects = models.Manager()

    def __str__(self):
        
        return self.name


class FAQ(models.Model):
    """
    A model for handling frequently asked questions that appear on the main page.
    """

    question = models.CharField(max_length=400)
    answer = models.CharField(max_length=500)

    objects = models.Manager()

    def __str__(self):

        return self.question[50:] + '...' if len(self.question) > 50 else self.question


class IndexInfo(models.Model):
    """
    A model for handling the information that goes to the main and base pages.
    """

    class Meta:

        verbose_name = 'Index information'
        verbose_name_plural = 'Index information'

    brand = models.ImageField(upload_to='images', null=True)
    brand_height = models.PositiveIntegerField(null=True)
    title = models.CharField(max_length=200, null=True)
    product_title = models.CharField(max_length=200)
    product_info = models.TextField()
    company_requisities = models.CharField(max_length=200, null=True)
    footer_motto = models.CharField(max_length=300)
    media = models.ManyToManyField(SocialMedia)
    date_added = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        
        return self.title


class Place(models.Model):
    """
    A model for handling how many places are in total available for a course and how many of them are taken.
    """

    available_places = models.PositiveIntegerField(null=True)
    booked_places = models.PositiveIntegerField(null=True)

    objects = models.Manager()

    def __str__(self):

        return self.available_places

lp/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
#from django_ratelimit.decorators import ratelimit
from .models import Book, FAQ, IndexInfo, Place


#@ratelimit(key='ip', rate='10/m')
def index(request: HttpRequest):
    """
    The home page.
    """
    
    information = None
    place = None
    faq = FAQ.objects.all()
    try:
        information = IndexInfo.objects.latest('date_added')
        place = Place.objects.latest('id')
    except (IndexInfo.DoesNotExist, Place.DoesNotExist):
        pass

    context = {
        'information': information,
        'place': place,
        'faq': faq,
    }
    return render(request, 'lp/index.html', context)


#@ratelimit(key='ip', rate='10/m')
def get_main_information(request: HttpRequest):
    """
    A view for retrieving data on social media for the base html and returning it as a JsonResponse.

    Raises Http404 in case no data found.
    """

    has_te = 'Transfer-Encoding' in request.headers
    has_cl = 'Content-Length' in request.headers
    if has_te and has_cl:
        raise PermissionDenied

    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax and request.method == 'GET':
        information = None
        try:
            information = IndexInfo.objects.latest('date_added')
        except IndexInfo.DoesNotExist:
            pass
        book = None
        try:
            book = Book.objects.latest('id')
        except Book.DoesNotExist:
            pass
        brand = render_to_string(
            'lp/includes/brand.html',
            {
                'brand_image': information.brand.url if information.brand else None, 
                'height': information.brand_height if information.brand_height else None,
            }
        ) if information else None
        footer = render_to_string(
            'lp/includes/information-for-footer.html',
            {
                'information': information, 
                'media': information.media.all().order_by('name') if information else None, 
                'user': request.user,
            },
        )
        return JsonResponse({'brand': brand, 'footer': footer, 'book_link': book.file.url if book else None})
    raise PermissionDenied

lp/templates/lp/includes/brand.html
{% if brand_image %}
    <a class="navbar-brand" href="/">
        <img src="{{ brand_image }}" height="{{ height }}"> Kelajak avlod
    </a>
{% endif %}

lp/templates/lp/includes/information-for-footer.html
{% load markdownify %}

{% if information %}
    {% if information.brand %}
        <a href="/">
            <img src="{{ information.brand.url }}" class="mb-3" height="{{ information.brand_height }}">
        </a>
    {% else %}
        <h3 class="fw-light mb-3">KELAJAK AVLOD</h1>
    {% endif %}
    <p class="fw-light">Copyright {% now 'Y' %}&copy; - Kelajak avlod</p>
    <p class="fw-light mx-auto" style="max-width: 600px;">
        {{ information.company_requisities|markdownify }}
    </p>
    <p class="fw-light mx-auto" style="max-width: 600px;">
        {{ information.footer_motto|markdownify }}
    </p>
    {% if not user.is_authenticated %}
        <a type="button" class="auth-link" data-bs-toggle="modal" data-bs-target="#login-modal">
            Kirish
        </a>
    {% else %}
        {% if user.is_admin or user.is_superuser %}
            <a type="button" class="auth-link me-3" href="{% url 'admin_panel:clients' %}">
                Admin
            </a>
        {% endif %}
        <a type="button" class="auth-link" href="{% url 'users:signout' %}">Chiqish</a>
    {% endif %}
    <div class="row" id="media-row">
        {% for sm in media %}
            <div class="col media-col">
                {% if sm.name == 'Gmail' or sm.name == 'gmail' %}
                    <a href="mailto:{{ sm.link }}">
                        <img src="{{ sm.icon.url }}" class="media">
                    </a>
                {% else %}
                    <a href="{{ sm.link }}">
                        <img src="{{ sm.icon.url }}" class="media">
                    </a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% else %}
    {% if not user.is_authenticated %}
        <a type="button" class="auth-link" data-bs-toggle="modal" data-bs-target="#login-modal">
            Kirish
        </a>
    {% else %}
        {% if user.is_admin or user.is_superuser %}
            <a type="button" class="auth-link me-3" href="{% url 'admin_panel:clients' %}">
                Admin
            </a>
        {% endif %}
        <a type="button" class="auth-link" href="{% url 'users:signout' %}">Chiqish</a>
    {% endif %}
{% endif %}