landing_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('clients-management-system/', admin.site.urls),
    path('', include('lp.urls', namespace='lp')),
    path('admin-panel/', include('admin_panel.urls', namespace='admin_panel')),
    path('authentication/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lp/urls.py
from django.urls import path
from . import views


app_name = 'lp'
urlpatterns = [
    path('', views.index, name='index'),
    path('get-main-information-32n42n56bh67bkj45kjnk324n5/', views.get_main_information, name='get-main-information'),
]

users/urls.py
from django.urls import path
from . import views
from .assistants import generate_token


app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('get-phone-number-jnsdfc242cc4342c323ch2h3ch234c23/', views.get_phone_numbers, name='get-phone-numbers'),
]

lp/models.py
from django.db import models
from .relations import SocialMedia


class Book(models.Model):
    """
    A model for handling books released by the learning center.
    """

    name = models.CharField(max_length=200)
    file = models.FileField(upload_to='files')

    objects = models.Manager()

    def __str__(self):
        
        return self.name


class FAQ(models.Model):
    """
    A model for handling frequently asked questions that appear on the main page.
    """

    question = models.CharField(max_length=400)
    answer = models.CharField(max_length=500)

    objects = models.Manager()

    def __str__(self):

        return self.question[50:] + '...' if len(self.question) > 50 else self.question


class IndexInfo(models.Model):
    """
    A model for handling the information that goes to the main and base pages.
    """

    class Meta:

        verbose_name = 'Index information'
        verbose_name_plural = 'Index information'

    brand = models.ImageField(upload_to='images', null=True)
    brand_height = models.PositiveIntegerField(null=True)
    title = models.CharField(max_length=200, null=True)
    product_title = models.CharField(max_length=200)
    product_info = models.TextField()
    company_requisities = models.CharField(max_length=200, null=True)
    footer_motto = models.CharField(max_length=300)
    media = models.ManyToManyField(SocialMedia)
    date_added = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        
        return self.title


class Place(models.Model):
    """
    A model for handling how many places are in total available for a course and how many of them are taken.
    """

    available_places = models.PositiveIntegerField(null=True)
    booked_places = models.PositiveIntegerField(null=True)

    objects = models.Manager()

    def __str__(self):

        return self.available_places

lp/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
#from django_ratelimit.decorators import ratelimit
from .models import Book, FAQ, IndexInfo, Place


#@ratelimit(key='ip', rate='10/m')
def index(request: HttpRequest):
    """
    The home page.
    """
    
    information = None
    place = None
    faq = FAQ.objects.all()
    try:
        information = IndexInfo.objects.latest('date_added')
        place = Place.objects.latest('id')
    except (IndexInfo.DoesNotExist, Place.DoesNotExist):
        pass

    context = {
        'information': information,
        'place': place,
        'faq': faq,
    }
    return render(request, 'lp/index.html', context)


#@ratelimit(key='ip', rate='10/m')
def get_main_information(request: HttpRequest):
    """
    A view for retrieving data on social media for the base html and returning it as a JsonResponse.

    Raises Http404 in case no data found.
    """

    has_te = 'Transfer-Encoding' in request.headers
    has_cl = 'Content-Length' in request.headers
    if has_te and has_cl:
        raise PermissionDenied

    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax and request.method == 'GET':
        information = None
        try:
            information = IndexInfo.objects.latest('date_added')
        except IndexInfo.DoesNotExist:
            pass
        book = None
        try:
            book = Book.objects.latest('id')
        except Book.DoesNotExist:
            pass
        brand = render_to_string(
            'lp/includes/brand.html',
            {
                'brand_image': information.brand.url if information.brand else None, 
                'height': information.brand_height if information.brand_height else None,
            }
        ) if information else None
        footer = render_to_string(
            'lp/includes/information-for-footer.html',
            {
                'information': information, 
                'media': information.media.all().order_by('name') if information else None, 
                'user': request.user,
            },
        )
        return JsonResponse({'brand': brand, 'footer': footer, 'book_link': book.file.url if book else None})
    raise PermissionDenied

lp/templates/lp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Kelajak avlod{% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/lp.css' %}">
        <link rel="shortcut icon" href="{% static 'icons/favicon.png' %}">
        <script language="JavaScript" type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script language="JavaScript" type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    </head>
    <body id="lp_body">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" id="navbar-main">
            <div class="container-fluid" id="brand-container"></div>
        </nav>
        {% block content %}{% endblock content %}
        <div class="modal fade" tabindex="-1" id="login-modal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="fw-light mt-2 ms-2">Shaxsiy kabinetga kirish</h3>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="text-start mb-3 ms-2 me-2">
                            <label class="form-label fw-light" for="phone_number_login">
                                Telefon raqam
                            </label>
                            <input class="register-input"
                            name="phone_number"
                            type="tel"
                            placeholder="+998901234567"
                            maxlength="13"
                            id="phone_number_login">
                        </div>
                        <div class="text-start mb-2 ms-2 me-2">
                            <label class="form-label fw-light" for="password_login">
                                Parol
                            </label>
                            <input class="register-input"
                            name="password"
                            type="password"
                            placeholder="********"
                            id="password_login">
                        </div>
                        <p class="error fw-bold ms-2 mb-0" id="error">
                            Telefon raqam yoki parol noto'g'ri kiritildi!
                        </p>
                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn-submit" onclick="return ValidateLoginForm()" id="login-btn">
                            Kirish &raquo;
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container footer-container" id="footer-container"></div>
    </body>
    <script>
        // Global variables or constants go here
        const submit_btn = document.getElementById('login-btn');
        
        // Event based functions go here
        jQuery.ajax({
            url: '{% url "lp:get-main-information" %}',
            type: 'GET',
            dataType: 'json',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
            success: function (data) {
                const brand_container = document.querySelector('#brand-container');
                const footer = document.querySelector('#footer-container');
                const download_btn = document.querySelector('#download-btn');
                brand_container.innerHTML = data.brand;
                footer.innerHTML = data.footer;
                if (download_btn) {
                    download_btn.href = data.book_link;
                };
            },
        });

        // Functions/methods go here
        function ValidateLoginForm() {
            var phone_number_valid = ValidateLoginPhoneNumber('#phone_number_login');
            var password_valid = ValidateLoginPassword('#password_login');
            
            if (phone_number_valid && password_valid) {
                $('#error').css('display', 'none');
                jQuery.ajax({
                    url: '{% url "users:signin" %}',
                    type: 'POST',
                    dataType: 'json',
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                    },
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        phone_number: $('#phone_number_login').val(),
                        password: $('#password_login').val(),
                    },
                    success: function (data) {
                        if (String(data.status) === 'signedin') {
                            window.location.reload();
                        };
                    },
                    error: function (error) {
                        $('#phone_number_login').css('border-color', 'red');
                        $('#password_login').css('border-color', 'red');
                        $('#error').css('display', 'block');
                        return false;
                    },
                });
            } else {
                $('#phone_number_login').css('border-color', 'red');
                $('#password_login').css('border-color', 'red');
                $('#error').css('display', 'block');
                return false;
            }
        };

        function ValidateLoginPassword(field) {
            let value = String($(field).val());
            if (
                    value &&
                    is_space_only(value) === false &&
                    value.length >= 8
            ) {
                $(field).css('border-color', '#000');
                return true;
            } else {
                $(field).css('border-color', 'red');
                return false;
            };
        };

        function ValidateLoginPhoneNumber(field) {
            let value = String($(field).val());
            if (value.startsWith('+998') === true && isnumeric(value.slice(1)) === true && value.length === 13) {
                $(field).css('border-color', '#000');
                return true;
            } else {
                $(field).css('border-color', 'red');
                return false;
            }
        };

        function is_space_only(string) {
            return /^\s+$/.test(string);
        };

        function isnumeric(string) {
            return /^\d+$/.test(string);
        };
    </script>
</html>

lp/templates/lp/index.html
{% extends 'lp/base.html' %}
{% load static %}
{% load markdownify %}

{% block content %}
<h2 class="fw-light text-center display-6 mt-5">
    {{ information.title|markdownify }}
</h2>
<div class="progress-header">
    <div class="col">
        Band o'rinlar
    </div>
    <div class="col" id="progress-percent"></div>
</div>
<div class="progress-bar">
    <div class="progress" id="progress"></div>
</div>
<div class="container product-container">
    {% if user.is_authenticated %}
        <h3>{{ information.product_title|markdownify }}</h3>
        <p class="product-information fw-light">
            {{ information.product_info|markdownify }}
        </p>
    {% endif %}
    {% if not user.is_authenticated %}
        <form action="{% url 'users:register' %}" 
        class="register-form mx-auto" 
        novalidate 
        method="post"
        id="register-form" onsubmit="return ValidateForm()">
            {% csrf_token %}
            <div class="register-div mt-3">
                <label class="form-label fw-light" for="names">
                    FISh(Familiya Ism Sharif)<span style="color: red; font-weight: bold;">*</span>
                </label>
                <input class="register-input"
                name="names"
                type="text"
                placeholder="Boltayev Bolta Boltayevich"
                maxlength="180"
                id="names">
                <p class="error fw-light mb-0" id="names-error">FISh noto'g'ri kiritildi!</p>
            </div>
            <div class="register-div mt-3">
                <label class="form-label fw-light" for="phone_number">
                    Telefon raqam<span style="color: red; font-weight: bold;">*</span>
                </label>
                <input class="register-input"
                name="phone_number"
                type="tel"
                placeholder="+998901234567"
                maxlength="13"
                id="phone_number">
                <p class="error fw-light mb-0" id="phone-number-error">Telefon raqam noto'g'ri kiritildi!</p>
                <p class="error fw-light mb-0" id="phone-number-exists-error">
                    Kiritilgan telefon raqam orqali ro'yxatdan o'tilgan!
                </p>
            </div>
            <div class="register-div mt-3">
                <label class="form-label fw-light" for="address">
                    Manzil<span style="color: red; font-weight: bold;">*</span>
                </label>
                <input class="register-input"
                name="address"
                type="text"
                placeholder="Qarshi shahri, X mahallasi Y ko`chasi Z-uy"
                maxlength="250"
                id="address">
                <p class="error fw-light mb-0" id="address-error">Manzil noto'g'ri kiritildi!</p>
            </div>
            <div class="register-div mt-3">
                <label class="form-label fw-light" for="childs_class">
                    Farzandingizni maktabi va sinfi<span style="color: red; font-weight: bold;">*</span>
                </label>
                <input class="register-input"
                name="childs_class"
                type="text"
                placeholder="XX-maktab, 3-V"
                maxlength="20"
                id="childs_class">
                <p class="error fw-light mb-0" id="childs-class-error">
                    Farzandingizni maktabi va sinfi noto'g'ri kiritildi!
                </p>
            </div>
            <p class="fw-light mt-2">
                <span style="color: red; font-weight: bold;">*</span>Majburiy maydonlar
            </p>
            <div class="mt-4 w-100 text-center">
                <button type="submit" 
                class="btn-submit"
                id="submit">
                    Ro'yxatdan o'tish &raquo;
                </button>
            </div>
        </form>
    {% endif %}
</div>
{% if user.is_authenticated %}
    <div class="rate-row row">
        <div class="col-md rate-col-1">
            <div class="rate">
                <h3 class="text-center">Oddiy tarifi</h3>
                <img src="{% static 'icons/check.png' %}" height="20"> Qo'llanma bo'yicha video tahlillar<br/><br/>
                <img src="{% static 'icons/check.png' %}" height="20"> O'zlashtirilgan bilimlar bo'yicha haftalik testlar<br/><br/>
                <img src="{% static 'icons/cross.png' %}" height="20"> 24 soat ustozlar bilan aloqa<br/><br/>
                <img src="{% static 'icons/cross.png' %}" height="20"> Ingliz tili darsliklari<br/><br/>
                <img src="{% static 'icons/cross.png' %}" height="20"> Ustozlardan to'g'ri bilim olish bo'yicha tavsiyalar<br/><br/>
                <h4 class="text-center mb-4">127 000 so'm</h4>
                <h6 class="text-center mb-0" style="color: red;">
                    Bog'lanish uchun shu yerga bosing &downarrow;
                </h6>
                <a type="button" class="btn-submit text-center mt-3" href="https://t.me/kelajakavlod01">
                    Kelajak avlod admin &raquo;
                </a>
            </div>
        </div>
        <div class="col-md rate-col-2">
            <div class="rate">
                <h3 class="text-center">Ajoyib tarifi</h3>
                <img src="{% static 'icons/check.png' %}" height="20"> Qo'llanma bo'yicha video tahlillar<br/><br/>
                <img src="{% static 'icons/check.png' %}" height="20"> O'zlashtirilgan bilimlar bo'yicha haftalik testlar<br/><br/>
                <img src="{% static 'icons/check.png' %}" height="20"> 24 soat ustozlar bilan aloqa<br/><br/>
                <img src="{% static 'icons/check.png' %}" height="20"> Ingliz tili darsliklari<br/><br/>
                <img src="{% static 'icons/check.png' %}" height="20"> Ustozlardan to'g'ri bilim olish bo'yicha tavsiyalar<br/><br/>
                <h4 class="text-center mb-4">187 000 so'm</h4>
                <h6 class="text-center mb-0" style="color: red;"`>
                    Bog'lanish uchun shu yerga bosing &downarrow;
                </h6>
                <a type="button" class="btn-submit text-center mt-3" href="https://t.me/kelajakavlod01">
                    Kelajak avlod admin &raquo;
                </a>
            </div>
        </div>
    </div>
    <h3 class="text-center">
        Hoziroq xarid qilsangiz <span class="discount-percent">10%</span> chegirma!
    </h3>
{% endif %}
<div class="container text-center w-100 p-5">
    {% if user.is_authenticated %}
        <a type="button" class="btn-download" id="download-btn" download>
            Kitobni yuklash <img src="{% static 'icons/download-icon.png' %}" class="ms-2" height="20">
        </a>
    {% else %}
        <h4 class="mb-4" style="color: red;">Kitobni yuklab olish uchun avval ro'yxatdan o'ting</h4>
        <a type="button" class="btn-download disabled" id="download-btn-disabled">
            Kitobni yuklash <img src="{% static 'icons/download-icon.png' %}" class="ms-2" height="20">
        </a>
    {% endif %}
</div>
{% if user.is_authenticated %}
    <div class="container product-container">
        <h3 class="fw-normal">Tez-tez so'raladigan savollar</h3>
        {% for question in faq %}
            <h6 class="fw-light">Savol: {{ question.question|markdownify }}</h6>
            <h6 class="fw-light">Javob: {{ question.answer|markdownify }}</h6>
        {% empty %}
            <h3 class="fw-light text-center mt-5 mb-5">Ma'lumotlar mavjud emas...</h3>
        {% endfor %}
    </div>
{% endif %}
<script>
    // Global variables or constants go here
    var usernames = [];

    // Event based functions go here
    $(document).ready(function () {
        let bold_texts = document.querySelectorAll('strong:not(#user-text)');
        for (let i = 0; i < bold_texts.length; i++) {
            let element = bold_texts[i]
            let text = element.textContent;
            element.innerHTML = "<u>" + text + "</u>";
        };
        let booked_places_percent = Percentify('{{ place.available_places }}', '{{ place.booked_places }}');
        document.getElementById('progress-percent').textContent = Math.ceil(booked_places_percent) + '%';
        $('#progress').css('width', String(Math.ceil(booked_places_percent) + '%'));
    });
    jQuery.ajax({
        url: '{% url "users:get-phone-numbers" %}',
        type: 'GET',
        dataType: 'json',
        headers: {
            'X-Requested-With': 'XMLHttpRequest',
        },
        success: function (data) {
            for (let i = 0; i < data.phone_numbers.length; i++) {
                usernames.push(String(data.phone_numbers[i]));
            };
        },
    });

    // Functions/methods go here
    function Percentify(total, value) {
        return value / total * 100;
    };

    function ScrollToPC(element) {
        element.scrollIntoView(
            {
                block: (window.innerWidth < 768) ? 'start':'center',
                behavior: 'smooth',
            }
        );
    };

    function ValidateAddress(field, error) {
        let value = String($(field).val());
        if (
                value &&
                is_space_only(value) === false && 
                value.length > 10
        ) {
            $(field).css('border-color', '#000');
            $(error).css('display', 'none');
            return true;
        } else {
            $(field).css('border-color', 'red');
            $(error).css('display', 'block');
            return false;
        };
    };

    function ValidateChildsClass(field, error) {
        let value = String($(field).val());
        if (
                value &&
                is_space_only(value) === false
                && value.length > 5
        ) {
            $(field).css('border-color', '#000');
            $(error).css('display', 'none');
            return true;
        } else {
            $(field).css('border-color', 'red');
            $(error).css('display', 'block');
            return false;
        };
    };

    function ValidateForm() {
        var name_valid = ValidateName('#names', '#names-error');
        var phone_number_valid = ValidatePhoneNumber('#phone_number', '#phone-number-error');
        var address_valid = ValidateAddress('#address', '#address-error');
        var childs_class_valid = ValidateChildsClass('#childs_class', '#childs-class-error');
        
        if (
                name_valid && 
                phone_number_valid && 
                address_valid &&  
                childs_class_valid
        ) {
            if (usernames.includes(String($('#phone_number').val())) === false) {
                return true
            } else {
                $('#phone_number').css('border-color', 'red');
                $('#phone-number-exists-error').css('display', 'block');
                return false;
            }
        } else {
            return false;
        }
    };

    function ValidateName(field, error) {
        let value = String($(field).val());
        if (
                value &&
                is_space_only(value) === false &&
                value.split(' ').length > 2
        ) {
            $(field).css('border-color', '#fff');
            $(error).css('display', 'none');
            return true;
        } else {
            $(field).css('border-color', 'red');
            $(error).css('display', 'block');
            return false;
        };
    };

    function ValidatePhoneNumber(field, error) {
        let value = String($(field).val());
        if (value.startsWith('+998') === true && isdigit(value.slice(1)) === true && value.length === 13) {
            $(field).css('border-color', '#000');
            $(error).css('display', 'none');
            return true;
        } else {
            $(field).css('border-color', 'red');
            $(error).css('display', 'block');
            return false;
        }
    };

    function is_space_only(string) {
        return /^\s+$/.test(string);
    };

    function isdigit(string) {
        return /^\d+$/.test(string);
    };
</script>
{% endblock content %}